### ISSUE TITLE
build the shelley-spec-ledger-test package in CI

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#1503]
We do not currently build the package `shelley-spec-ledger-test` in CI, and it is easy to break it without realizing.

**Comment by mrBliss** [comment]
@JaredCorduan Recently, I came up with a different approach in consensus: we had `ouroboros-consensus-shelley` which contained both `src` and `test`. We wanted to depend on the generators in `ouroboros-consensus-shelley/test` from another package, but we can't depend on a testsuite of another package. Instead of letting `ouroboros-consensus-shelley/test` double as testsuite *and* a package, which causes PRs like #1502 (I'm the cause of it all, sorry!), I did the following: create a separate package `ouroboros-consensus-shelley-test` that contains the generators and other reusable test infrastructure in `src` and the actual tests/properties in `test`.

Maybe you could follow the same approach?

**Comment by JaredCorduan** [comment]
ok, thank you for the idea @mrBliss !

**Comment by nc6** [comment]
We are already building `shelley-spec-ledger-test` in CI - see for example https://hydra.iohk.io/build/3198007. So closing this as done :-)
