### ISSUE TITLE
Genesis hash fo ShelleyGenesis file

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-ledger#1531]
This is not a must have, but is a "nice to have".

For pure Shelley networks (eg testnets that do not follow on from Byrin), it would be nice to have a way of canonically hashing the shelley genesis file so that the first block in a pure Shelley chain can use the hash of the genesis file as the hash of the first block's previous block.

**Comment by mrBliss** [comment]
I'm bumping this to a higher priority because we need the genesis hash for https://github.com/input-output-hk/ouroboros-network/issues/2235, which is needed for a Byron-to-Shelley mainnet.

What I have in mind is something like the [`GenesisHash` of Byron](https://input-output-hk.github.io/ouroboros-network/cardano-ledger/Cardano-Chain-Genesis-Hash.html#t:GenesisHash). Just a newtype around a hash. It should at least have a `NoUnexpectedThunks` instance. This value will be read from the CLI/configuration file (not the genesis file itself of course) and passed to `ouroboros-consensus` as part of the `ProtocolInfo` for Shelley. Should it use the same `HASH` type? Are the CLI tools to quickly compute that HASH of the genesis.json file?

**Comment by nc6** [comment]
It would be nice to clarify exactly the requirements of this task. The original issue from @erikd refers to a separate thing than the comment from @mrBliss. I'll try to describe what I think the possibilities here are:

- @mrBliss's comment seems to refer mostly to a value used for the initial nonce. If this is the only thing needed, I'm not clear what's required from the ledger here, which treats the initial nonce just as a random value. Do we want to _verify_ that the initial nonce matches some derivation from the genesis? That would seem odd in the ledger, which cares neither about the initial nonce nor about `ShelleyGenesis`.

- @erikd, on the other hand, talks about a hash included in the first block referring to Shelley genesis. We used to have this, but it was removed (by Jared, in https://github.com/input-output-hk/cardano-ledger-specs/pull/1326), I think in response to requirements from consensus. Currently the issue with adding an initial hash is that we use `WithOrigin LastAppliedBlock` in certain state, and we cannot therefore include a hash inside `Origin`. Without understanding why these changes were made, I'm hesitant to remove them.

**Comment by mrBliss** [comment]
I had a discussion with @nc6 and we decided that it's best to just use the `Nonce` type directly for this, both in `cardano-ledger-specs` (to avoid confusion as `Genesis(Config)Hash` would not be related to the existing `GenesisHash` and genesis in any way) and in `ouroboros-consensus` (we just need a `Nonce` for entropy, we also don't care where it comes from). Only in `cardano-node`, where they have to provide that `Nonce` to consensus (via `ProtocolInfo`, is the choice made to use the hash of the Shelley genesis JSON file.

For a Byron-to-Shelley mainnet, we don't care about `Origin` being replaced with the actual genesis hash, it will be the hash of the last Byron block. It only matters for fresh Shelley nets, which are not the highest priority.

**Comment by nc6** [comment]
I think we will not address this issue further; it would require various changes in consensus and our interface to do so.
