### ISSUE TITLE
Strip double quotes from DNS names in PoolRelay struct

### ISSUE THREAD

**Issue by erikd** [IntersectMBO/cardano-ledger#1586]
I have just added the code to add pool relays to `db-sync`.

It seems that some DNS names are double quoted and others are not eg:
```
  1 |       6 |                 |      | relays-new.shelley-testnet.dev.cardano.org |              | 3001
...
 27 |      89 |                 |      | "relays.stakepool.at"                      |              | 3001
```
The double quotes should be stripped from the names before they are inserted into the `PoolRelay` struct.

@disassembler suggests either strip or don't accept them as valid.

Based on comments from @dcoutts I would suggest that the ledger should do basic sanity checking (ie that IP addresses are RFC compliant) that do not require a DNS lookup.

**Comment by erikd** [comment]
The `ip`  library should do all the validation we need for IP addresses, but basic validation is still need for host names.

**Comment by erikd** [comment]
The only validation I asked for was that the address actually parsed as a valid hostname.

However, the ticket was actually about stripping double quotes from the name which we absolutely should do.

**Comment by JaredCorduan** [comment]
@dcoutts do you have an opinion about this?

**Comment by dcoutts** [comment]
Generally my view is that there's a million and one ways that SPOs can provide incorrect info, or otherwise mess up their own block producer or relay configuration. We cannot protect people from themselves. But getting this stuff right is in the interest of the SPOs because they need other SPOs to pick their relays as upstream peers to be able to get their blocks out.

So I don't think we should have the ledger get involved in trying to sift out garbage values. The network p2p layer has to be able to deal with syntactic garbage as well as with unreachable IPs, or valid DNS names that resolve to nonsense.

As part of the p2p testnet and mainnet roll out we'll have a programme to educate folks on how to set up and register their relays. Re-registering the pool is cheap, so it's not hard for operators to fix their syntax.

If we want helpful validation, that should go in the cli, but not in the ledger.
