### ISSUE TITLE
Make the Shelley transaction generator configurable

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/cardano-ledger#1689]
Slack message in `#rule-based-spec-sl` for further context: https://input-output-rnd.slack.com/archives/CCRB7BU8Y/p1595347524107500

The two example options that I'm currently aware of:

  1) We'd like to be able to ensure the generated transactions have no certificate changes.

  2) We'd like to be able to ensure that the generated transactions have no protocol parameter updates.

**Comment by nfrisby** [comment]
Just a though, @uroboros: this configuration record could also perhaps contain (nullary) continuations to replace the current uses of `QC.discard` in the utxo generator we were discussing.

**Comment by uroboros** [comment]
@nfrisby there are existing constants that can give you what you want

(1) suppress transaction Certificate generation with `maxCertsPerTx = 0`
(2) suppress transaction Update generation with `frequencyTxUpdates=0`

I like your idea of the continuation instead of the discard, let me try something like that out (and keep this issue as a handle for that)

**Comment by nfrisby** [comment]
> @nfrisby there are existing constants that can give you what you want

Aha! I had assumed `Constants` were the protocol-level constants (eg slot length, stability window, etc). Thank you for the clarification.

**Comment by uroboros** [comment]
The linked PR baked "retry" into the transaction generator - I think that wraps up this issue https://github.com/input-output-hk/cardano-ledger-specs/pull/1731
