### ISSUE TITLE
add 2, shelleyblock ?

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#1715]
https://github.com/input-output-hk/cardano-ledger-specs/blob/183a70c001587d9b1977541deae28c3e44713907/byron/cddl-spec/byron.cddl#L4

**Comment by SebastienGllmt** [comment]
Is that needed given that the shelley.cddl has its own block definition? https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/cddl-files/shelley.cddl

**Comment by ashisherc** [comment]
1.18.0 has that extra 2 in the block received, looks like the shelley cddl block fits here as

[2, shelley_block]

**Comment by mrBliss** [comment]
@ashisherc Those extra bytes you're seeing is because of the Hard Fork Combinator. You see, the Cardano block chain consists of both the Byron era and the Shelley era (and many more to come in the future). When sending/receiving a block/header/transaction/... (x) across the network, we need to be able to detect whether it is a Byron x or a Shelley x.

For headers, transactions, ..., we use `[0, byron_x]` and `[1, shelley_x]` where that first number is a tag indicating the era.

For blocks, we had to maintain backwards compatibility and use `[0, byron_epoch_boundary_block]`, `[1, byron_regular_block]`, `[2, shelley_block]`.

To see more examples of this, you can have a look the golden output in https://github.com/input-output-hk/ouroboros-network/tree/master/ouroboros-consensus-cardano/test/golden/CardanoNodeToNodeVersion2.

This should also answer https://github.com/input-output-hk/cardano-ledger-specs/issues/1713 and https://github.com/input-output-hk/ouroboros-network/issues/2467.

**Comment by ashisherc** [comment]
yes, that answers everything. Can the specs be updated to reflect this?

**Comment by mrBliss** [comment]
> Can the specs be updated to reflect this?

Note that `cardano-ledger-specs` is entirely agnostic of the Hard Fork Combinator.

**Comment by ashisherc** [comment]
Okay, I would like to suggest a place to see all the docs related to networking and ledger specs, which shows all the latest changes.

Someone building on top of this specification will have a hard day figuring out the changes.
