### ISSUE TITLE
Stake Reference in Shelley Addresses Makes Accounts Linkable

### ISSUE THREAD

**Issue by Zaytion** [IntersectMBO/cardano-ledger#1766]
The Stake Reference component in a Shelley address makes all addresses of a Shelley wallet linkable. This is a privacy concern. 

I raised this on reddit when I was confused by it and erikd over there, who is a confirmed member of IOHK, chimed in. After a short discussion he gave his analysis and suggested I raise an issue here. He also suggested I link to that analysis:

https://old.reddit.com/r/cardano/comments/i66caq/shelley_addresses_have_same_character_string_in/g0uskgi/

I apologize if I've done anything wrong with this issue, this is my first time ever creating an issue on Github.

**Comment by JaredCorduan** [comment]
Thank you for taking the time to make an issue @Zaytion ! This is actually not an issue with the ledger, which does not link payment and stake credentials together in any way. Daedalus is currently only using one stake key per wallet, which explains what you are seeing. I agree that the wording "to protect your privacy, always use a new address when requesting funds" is problematic. I'll see if I can move this issue somewhere better.

**Comment by dcoutts** [comment]
That's correct, depending on the policy that the wallet implementation uses.

See the Shelley specification (link to the latest version is in the top level of this repo) where it discusses privacy, for example from Section 6:

> Having an efficient delegation mechanism – and in particular a mechanism where delegation is rewarded – requires a slight compromise on the level of pseudonymity, since addresses using the same stake address will be linkable. However,
users can decide to use a number of different accounts, with separate stake addresses, if they are willing to pay the fees for using multiple stake addresses. This will give them a level of pseudonymity that is not worse than that in the Ethereum network.
>
> They can also choose to use a distinct stake address per value address, or value addresses with no stake address at all, which gives pseudonymity that is no worse than in Bitcoin.

So privacy-focused policies are possible within the Shelley rules, at the expense of bigger fees (due to having separate stake addresses).

So if you want a privacy-focused wallet, that's what you should be asking for. It's not a bug in the Shelley rules.
