### ISSUE TITLE
Discrepancies in NEWEPOCH when Rewards Update is Nothing

### ISSUE THREAD

**Issue by jmhrpr** [IntersectMBO/cardano-ledger#1805]
In [NEWEPOCH](https://github.com/input-output-hk/cardano-ledger-specs/blob/master/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/STS/NewEpoch.hs), the [formal spec](https://hydra.iohk.io/build/3893468/download/1/ledger-spec.pdf) (page 68) states that the "first rule describes the change in the case of e being equal to the next epoch e_l + 1. It also calls the MIR and EPOCH rules..." and that "the third rule deals with the case when the reward update is equal to nothing" and that "this rule does not change the state." This is shown in the figures in the formal spec, but in the executable spec it appears that even when the reward update is equal to nothing the MIR and EPOCH transitions are called and the epoch state is updated as in the first case.

**Comment by JaredCorduan** [comment]
great catch @jmhrpr !

In practice, we hope to never see this rule 31 fire, because that would mean that no block was produced during the last (7/10)-ths of the epoch. This would be a big problem for both the ledger and consensus.  But of course we need to specify what would happen! I think that what the implementation is doing (ie proceeding, just without applying any reward update) is just as defensible as what the spec says. All things being equal, I would rather not change the code at this point, so I will change the spec.

**Comment by jmhrpr** [comment]
Sounds good to me!
