### ISSUE TITLE
Rework overlay schedule to not use a map

### ISSUE THREAD

**Issue by nc6** [IntersectMBO/cardano-ledger#1825]
Currently the overlay schedule is set to use a Map of slots, which is pretty large for a full mainnet epoch. We can actually write it very easily to do without, by calculating some simple modular arithmetic. This works provided `d*f * slots per epoch` is an integer, so we should additionally check protocol updates for this property.

**Comment by mrBliss** [comment]
Making it a function instead of a `Map` is of course still the ideal solution, but in the meantime, executing the following idea by @edsko and me might already be a big improvement:

The size of an epoch is `10 * k / f`, which is 432,000 slots for mainnnet.

If our understanding is correct, then:

* `10 * k * d` slots in the overlay schedule are `ActiveSlot`.
* `10 * k * f * (1 - f)` slots in the overlay schedule are `NonActiveSlot`
* `10 * k * (1 - d)` slots are *not* in the overlay schedule and can be used for Praos

For `k = 2160`, `f = 0.05`, and different values of `d`:

  d | ActiveSlot | NonActiveSlot |  Praos |   Slots
----|------------|---------------|--------|--------
1.0 |     21,600 |       410,400 |      0 | 432,000
0.9 |     19,440 |       410,400 |  2,160 | 432,000
0.5 |     10,800 |       410,400 | 10,800 | 432,000
0.1 |      2,160 |       410,400 | 19,440 | 432,000
0.0 |          0 |       410,400 | 21,600 | 432,000

So the current implementation of the `OverlaySchedule` stores the sum of the 2nd (`ActiveSlot`) and 3rd (`NonActiveSlot`) in a `Map`.

What if instead of storing the `NonActiveSlot`s in the map, the Praos slots are stored? So instead of storing 410,400 times `NonActiveSlot`, store 0-21,600 `PraosSlot`s. This means that the size of the map will be 21,600 at all times instead of 410,400-432,000 (depending on `d`).

**Comment by mrBliss** [comment]
Note: since we store the `OverlaySchedule` in the ledger snapshots on disk, this change will break binary compatibility of the snapshots, rebuilding one one from genesis.. Consensus will already break compatibility in the next release, it would be great if this change could be done in the same release, requiring us to break compatibility (and inconveniencing wallet users and stake pool operators) once instead of twice.

**Comment by JaredCorduan** [comment]
the arithmetic works out like this:

letting
```
isOBFT      ::    
  Slot      ->  -- starting slot    
  Rational  ->  -- decentralization parameter    
  Slot      ->  -- slot to check    
  Bool    
isOBFT firstSlotNo dval slot = ceiling (s*dval) < ceiling ((s+1)*dval)    
  where    
    s = fromInteger $ slot - firstSlotNo
```

and

```
classifyOBFT ::    
  Slot     ->  -- starting slot    
  [a]      ->  -- genesis Nodes    
  Rational ->  -- decentralization parameter    
  Rational ->  -- active slot coefficent    
  Slot     ->  -- obft slot to classify    
  Maybe a      -- Nothing represents a silent slot, Just a means it is the genesis node a's turn    
classifyOBFT firstSlotNo gkeys dval ascValue slot =    
  if isActive    
    then    
      let genesisIdx = (position `div` ascInv) `mod` (fromIntegral $ length gkeys) in    
        gkeys `getAtIndex` genesisIdx    
    else Nothing    
  where    
    position = ceiling(fromInteger (slot - firstSlotNo) * dval)    
    isActive = position `mod` ascInv == 0    
    getAtIndex ls i = if i < length ls then Just (ls !! i) else Nothing    
    ascInv = floor (1/ascValue)
```

Then the overlay schedule that is current in master can be alternatively computed as:
```
simplified firstSlotNo gkeys dval ascValue slotsPerEpoch = Map.fromList $
  [ (s, classifyOBFT firstSlotNo gkeys dval ascValue s)                                                                          
    | s <-[0 ..(slotsPerEpoch-1)], isOBFT firstSlotNo dval s ]
```

What we can then do is completely remove the overlay schedule, and replace any lookup in it with the two functions `isOBFT` and `classifyOBFT`. We can do this in both the formal spec and the real implementation.
