### ISSUE TITLE
Help Reconstructing Merkle Root

### ISSUE THREAD

**Issue by FinleyMcIlwaine** [IntersectMBO/cardano-ledger#1974]
Hi all,

Apologies if this would be more appropriate in other channels. I've just had no luck on the forums or telegram so I thought I'd try asking here. Any help with this would be very much appreciated!

I'm putting together some lecture slides about blockchain for my university's data structures course. Of course I'll be mentioning Merkle trees. I'd like to show them a real world example by reconstructing the Merkle root of a Cardano block that we can view in one of the explorers. I've spent some time combing through the code here, but haven't made much progress beyond find the [Merkle module](https://github.com/input-output-hk/cardano-ledger-specs/blob/d5eaac6c4b21a8e69dc3a5503a72e3c3bfde648e/byron/ledger/impl/src/Cardano/Chain/Common/Merkle.hs), some of the [hash utilities](https://github.com/input-output-hk/cardano-ledger-specs/blob/d5eaac6c4b21a8e69dc3a5503a72e3c3bfde648e/byron/crypto/src/Cardano/Crypto/Hashing.hs) and the [TxProof example](https://github.com/input-output-hk/cardano-ledger-specs/blob/0644881f33777a769103518705da6b86f2ff3441/byron/ledger/impl/test/Test/Cardano/Chain/UTxO/Example.hs).

I imagine I'm missing some trivial information that would make this much easier, especially since the transaction hashes are already available on many of the explorers.

Thanks in advance for any help or direction!

**Comment by dcoutts** [comment]
Hi Finley. Thanks for the question. 

BTW, the best first place to look to get info on design questions would usually be in the Shelley design specification rather than the code.  https://github.com/input-output-hk/cardano-ledger-specs#cardano-ledger 

Cardano from Shelley onwards does not use a Merkel tree of transactions within each block because it provides no benefit for Cardano. The Cardano Byron implementation did use Merkel trees, but it provided no benefit and had non-trivial costs so we removed it for the Shelley era.

The usual purpose of using a Merkel tree of transactions in blocks is to allow for lightweight clients that can validate the chain headers but avoid downloading block bodies. This is not possible with a plain PoS system since the header validation depends on knowing the recent stake distribution which in turn depends on the transactions in the block bodies from previous epochs.

Also, compared to bitcoin, Cardano blocks are very frequent but typically quite small, so the benefit from not downloading block bodies is much less. The big win for lightweight clients would be some secure snapshotting scheme where they can catch up to the current state of the chain in a secure manner without downloading the entire chain history.
