### ISSUE TITLE
Implemented type of Value mismatch

### ISSUE THREAD

**Issue by nankeen** [IntersectMBO/cardano-ledger#2175]
There's an extra Integer field before the maps, in Figure 1 of GL-D1 Value is a derived type of PolicyID → (AssetName → Quantity).

https://github.com/input-output-hk/cardano-ledger-specs/blob/a55a0458008bfe23a92fe25bb81b7b1c96f73827/shelley-ma/impl/src/Cardano/Ledger/Mary/Value.hs#L122

I believe this is used for the ADA quantity (for convenience perhaps?).

https://github.com/input-output-hk/cardano-ledger-specs/blob/a55a0458008bfe23a92fe25bb81b7b1c96f73827/shelley-ma/impl/src/Cardano/Ledger/Mary/Value.hs#L158

The spec alluded that it should be theoretically included in the map with (adaPolicy, adaName).

![Figure 1 extract](https://user-images.githubusercontent.com/6895854/110341300-19801580-8022-11eb-8f27-7e17767284f8.png)

**Comment by WhatisRT** [comment]
Yes, this is an intentional difference in the formal/executable specs. One of the reasons for this difference is memory efficiency: We require Ada deposits for outputs as protection against spam, and the smaller we can make an output, the smaller the required deposit is. This saves a `ScriptHash` on every output, which is quite substantial.

We probably don't want to change the executable spec, but what we could do is make `Value` abstract in the formal spec, and just require it to be a monoid with a function `Value -> P PolicyID` and morphisms `valueToCoin` and `coinToValue` that are inverses in one direction. Then, we could move the definition of `Value` into an appendix and explicitly mark it as a suggestion. I think I've suggested this before but it wasn't popular because this is more or less the key definition of the entire spec.

**Comment by JaredCorduan** [comment]
I like your suggestion @WhatisRT

**Comment by polinavino** [comment]
There are now 3-4 different implementations of Value. The one we described as the main one in the spec is
`PolicyID x AssetName -> Quantity` 
This is the one used in the CLI. The code implements optimized versions that are isomorphic to this representation.

Done in https://github.com/input-output-hk/cardano-ledger-specs/pull/2383
