### ISSUE TITLE
alonzo CDDL - describe delta_coin at MIR cert that moves rewards to stake credential

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#2350]
There is a new type `delat_coin` for MIR cert used for moving funds to stakeCredential. Does this mean that `delat_coin` can be negative and that the funds can be taken from a stakeCredential and moved back to reserve?

https://github.com/input-output-hk/cardano-ledger-specs/blob/37066da0d2e1be6b53332cd6b6004614662b0988/alonzo/test/cddl-files/alonzo.cddl#L138

**Comment by JaredCorduan** [comment]
The semantics of the MIR cert will change slightly in the alonzo era. Funds **cannot be removed** from a stake credential by a MIR cert. A MIR cert can say "give Ashish 100 lovelace", and then "take 90 lovelace away from Ashish", since this results in a net positive change.

See https://github.com/input-output-hk/cardano-ledger-specs/pull/2146
