### ISSUE TITLE
alonzo CDDL - describe what is `script_data_hash` in trx body

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#2352]
There is a new field in transaction body `script_data_hash` is this the hash of `plutus_data` ?

**Comment by JaredCorduan** [comment]
we are still doing some small tweaks and syncs with the spec, but this is what the spec calls `wppHash`. the details for what exactly goes into this hash will have to be spelled out in prose in the CDDL (something we are working on). it's changed a bit from the spec since now it also has the datums. all should be clear soon! :)
