### ISSUE TITLE
is ada an asset or a token? both?

### ISSUE THREAD

**Issue by wolverineks** [IntersectMBO/cardano-ledger#2493]
if ada is an `asset`, and `token` is an on-chain representation of an `asset`,
what is the on-chain representation of ada?

https://github.com/input-output-hk/cardano-ledger-specs/blob/37322df14d44d1370e8a72b677815d64a92baa00/doc/explanations/token-bundles.rst#L11

**Comment by JaredCorduan** [comment]
In the implementation, `ADA` is a separate integer from the map-of-maps-of tokens.

https://github.com/input-output-hk/cardano-ledger-specs/blob/37322df14d44d1370e8a72b677815d64a92baa00/shelley-ma/impl/src/Cardano/Ledger/Mary/Value.hs#L134-L135

**Comment by wolverineks** [comment]
@JaredCorduan and for someone that doesnt read haskell?

**Comment by polinavino** [comment]
In the case of ada, ada the asset and its tokenized representation is one in the same (unlike tokens representing land or property or something). I hope this is what you were asking?

**Comment by wolverineks** [comment]
is ada the only "thing" that can be both an asset and an assetToken?

**Comment by wolverineks** [comment]
is it correct to say that conceptually there is only one ada and it is both an asset and an asset token?

**Comment by wolverineks** [comment]
is it correct to say that asset tokens are assets that have been tokenized?

**Comment by JaredCorduan** [comment]
Would the wire format (CDDL) be helpful? I can't tell if you are looking for clarification on the definitions, or if by the "on-chain representation of ada" you are looking for how the data is represented.

Since the Mary Era, transaction outputs contain a `value` instead of just `lovelace` (which we call `coin` in the CDDL). The line from the CDDL spec below says that a `value` is either a single `coin` (so ada-only) or a a pair of a `coin` (the lovelace) and the tokens:

https://github.com/input-output-hk/cardano-ledger-specs/blob/37322df14d44d1370e8a72b677815d64a92baa00/alonzo/test/cddl-files/alonzo.cddl#L362

**Comment by polinavino** [comment]
Ada is not the only asset and token - anyone can start another currency within Cardano that is not tied to any other digital or real-world data and/or items, probably not a very useful thing to mint, though, on average?
 
Asset tokens are tokens representing assets, whether these assets are just digital or real-world.

**Comment by wolverineks** [comment]
i thought that the real world data and/or items __are__ the asset? if a token is not tied to data/item, what is the asset that it represents?
do all tokens represent an asset? is this the case with ada?

**Comment by lehins** [comment]
@wolverineks Can I recommend you asking a question on StackOverflow: https://stackoverflow.com/questions/tagged/cardano or Reddit: https://www.reddit.com/r/cardano/ 

Github issue tracker is reserved for features and bugs. This is not really a place for Q&A
