### ISSUE TITLE
Collateral Return Outputs need minUTxO check

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#2725]
We need to validate collateral return outputs just like we check all other outputs. Eg, the minimum UTxO check. We can probably add a new class method to the `ExtendedUTxO` class.

**Comment by WhatisRT** [comment]
This is done by b1b7260b09341aac8662698a23578ebd868b8552 in the spec

**Comment by Soupstraw** [comment]
@WhatisRT 
* where do we look for scripts?
   * inputs
   * reference inputs
   * script witnesses
   * what about collateral inputs?
 * what about outputs?
   * scripts in auxillary data
 * which scripts are we supposed to validate as well-formed?
 * if we assume that datums are well-formed, because they have
   been successfully deserialized, why bother collecting them
   for these tests?

**Comment by WhatisRT** [comment]
We don't look for scripts in collateral inputs, any outputs or auxiliary data for the purpose of running them. For the well-formedness it's easy, any place where a script can appear in the transaction itself (i.e. not via lookup in the UTxO) we need to check. I.e. witnesses, outputs (including collateral) and auxiliary data.
For datums, we may or may not want to move the well-formedness check (length of bytestrings < 64) out of the deserialization. I don't really care where it's checked, it just has to be checked somewhere.

**Comment by JaredCorduan** [comment]
resolved by #2733
