### ISSUE TITLE
nativeMultiSigTag does not seem described in specifications

### ISSUE THREAD

**Issue by SmaugPool** [IntersectMBO/cardano-ledger#2756]
Native scripts hashes (policy ids) use a tag as described in https://github.com/input-output-hk/cardano-ledger/issues/1193.

This tag is set to 0 according to [nativeMultiSigTag](https://github.com/input-output-hk/cardano-ledger/blob/736c9295f5896de28fbcedc6a8fc4d509fb78d10/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Scripts.hs#L61-L65) and [hashMultiSigScript](https://github.com/input-output-hk/cardano-ledger/blob/736c9295f5896de28fbcedc6a8fc4d509fb78d10/shelley/chain-and-ledger/executable-spec/src/Shelley/Spec/Ledger/Scripts.hs#L163-L171) source code.

Shouldn't this tag and its value be part of CDDL specs?

Note that I have not found it either in formal specifications but maybe I just missed it.

**Comment by JaredCorduan** [comment]
great question @SmaugPool . There is no mention of this tag in the CDDL specification since it never actually show up on the wire, it's just used to create the script hash.

If the CDDL spec is where people think to look to find the tag, though, we could add a comment explaining which tag goes with which script type for the purpose of hashing. Or perhaps it could be in an appendix in the formal specs. I had thought we had it documented somewhere, but I am also failing to find it anywhere. It definitely should be documented, thank you for raising this!
