### ISSUE TITLE
Babbage - Question - Ledger Spec - potentially add info about out script ref

### ISSUE THREAD

**Issue by ashisherc** [IntersectMBO/cardano-ledger#2800]
https://github.com/input-output-hk/cardano-ledger/blob/76ae29dc6f73ee4707f3cf883a8af279501d798f/eras/babbage/test-suite/cddl-files/babbage.cddl#L90

Is the script required to be the output's witnessing script or can any plutus script be provided?

**Comment by JaredCorduan** [comment]
No, it can  be any script (timelocks too). The main purpose is to store a script in the ledger state so that you can use it in the future (multiple times) without having to provide it in the transaction (so with a reference input). [CIP-33](https://github.com/cardano-foundation/CIPs/pull/161) is a great read.
