### ISSUE TITLE
slotToPOSIXTime: incorrect translation for protocol version <= 5

### ISSUE THREAD

**Issue by francolq** [IntersectMBO/cardano-ledger#2842]
[`slotToPOSIXTime`](https://github.com/input-output-hk/cardano-ledger/blob/ded4296ee7dc26da3504b0148363de39edd6ff93/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L190) is always returning 1000000000000 when protocol version <= 5. It looks like it is incorrectly using the [`resolution`](https://hackage.haskell.org/package/base-4.14.1.0/docs/src/Data.Fixed.html#local-6989586621679548231) function.

The version is checked using function [`translateTimeForPlutusScripts`](https://github.com/input-output-hk/cardano-ledger/blob/7aae0d97b87fa508de8799510b49739b65e28335/eras/shelley/impl/src/Cardano/Ledger/Shelley/HardForks.hs#L54). In its documentation, the bug is kind of acknowledged:
```
-- | Starting with protocol version 6, we translate slots to time correctly for
-- Plutus scripts.
```
So, it seems like the incorrect behavior is preserved on purpose in the code, but I don't know why. :)

**Comment by JaredCorduan** [comment]
Hi @francolq , the bug is preserved on purpose in the code because if we wish to avoid splitting the network with an unintentional hard fork, we can only make semantic changes to the ledger via a controlled hard fork that bumps the major protocol version. After such a controlled hard fork (such as the position we are in now), we can go back and see if the semantic change is relevant to the history. In the event that it is not relevant, we do have the option of removing the bug. In other words, we could clean this up now if upon removing the bug we are able to sync mainnet. (and probably also our main testnet, which we would much prefer to not have to restart).

**Comment by JaredCorduan** [comment]
Thanks for raising this issue @francolq , it served as a reminder for me to see if we can go back and clean up the code (ie remove the bug).  Unfortunately, however, it turns out that we cannot. :(

I was able to sync mainnet with the bug removed, but the main testnet _does not_ sync. [This block](https://explorer.cardano-testnet.iohkdev.io/en/block?id=7828c58252b1eb59487fc363d88771b6e08fa52841f39e54bf39b5322e45efd4) here includes the famed :lobster: script (script hash is `9e7068208dae0dc0aea9e1b17e40ad3a606dead9bfbe4f1dadded7a6`), which triggers the bug.

**Comment by francolq** [comment]
Thank you @JaredCorduan for the quick and comprehensive answer. It is the first time I hear about this famed script. I guess it is good to see that the mainnet can be synced. If the testnet gets restarted some day, the bug can be removed.

**Comment by JaredCorduan** [comment]
[It](https://github.com/input-output-hk/lobster-challenge/blob/main/src/Cardano/PlutusLobster/LobsterScript.hs) was used to name the stuffed lobster in many of @CharlesHoskinson 's videos :)
