### ISSUE TITLE
Query a slice of pool distribution

### ISSUE THREAD

**Issue by jiagengliu** [IntersectMBO/cardano-ledger#2845]
Hello,

I am doing research on choosing a stake pool (coming from https://github.com/input-output-hk/cardano-ledger/issues/2745). I wonder what's the fastest way to get snapshots of pool information for each block similar to https://github.com/input-output-hk/cardano-ledger/issues/2657? Ideally, I am trying to get historical ledger states returned by [getRewardInfoPools](https://github.com/input-output-hk/cardano-ledger/blob/dd13fadabfe6760ec88caa9d605a67018633212b/eras/shelley/impl/src/Cardano/Ledger/Shelley/API/Wallet.hs#L371), including pools' live stake distribution, hit-rate estimate, non-myopic rewards (given a stake), etc, for each block in the history. 

Thanks a lot!
Jiageng

**Comment by JaredCorduan** [comment]
Sounds interesting! I think the best way to do it would be to use [foldBlocks](https://github.com/input-output-hk/cardano-node/blob/286a2b31c6858ee476c35be0fc0aa2bc0c9086b8/cardano-api/src/Cardano/Api/LedgerState.hs#L285). It connects to a running node and lets you fold over the blocks. It will give you the opportunity to look at the ledger state after each block. To get the ranking information, you'll want to use the ranking/API functions from the ledger repo.

For an example for how to use `foldBlocks`, you can check out the [stake credential history tool](https://github.com/input-output-hk/cardano-node/blob/master/cardano-client-demo/StakeCredentialHistory.hs). (Some of the [documentation for the tool](https://github.com/input-output-hk/cardano-node/blob/master/cardano-client-demo/Stake-Credential-History.md) might be of help).

Hope this helps! (I'm going to close this issue since the issues here are really for development work in this repo).
