### ISSUE TITLE
Incorrect conversion of validity interval's upper bound

### ISSUE THREAD

**Issue by ghost** [IntersectMBO/cardano-ledger#3043]
Recently, we have switched to cardano-ledger in plutus-apps instead of using our own validation rules. We have found that `transVITime` behaviour seems to be incorrect.

It takes the upper bound and uses `PV1.to` function that creates a closed upper bound.
```
transVITime pp ei sysS (ValidityInterval SNothing (SJust i)) = do
  t <- slotToPOSIXTime pp ei sysS i
  pure $ PV1.to t

...

to :: a -> Interval a
to s = Interval (LowerBound NegInf True) (upperBound s)

upperBound :: a -> UpperBound a
upperBound a = UpperBound (Finite a) True -- Boolean flag, whether a bound is inclusive or not.
```

While the validity interval is defined as a half open interval, open on the top.

```
-- | ValidityInterval is a half open interval. Closed on the bottom, open on the top.
--   A SNothing on the bottom is negative infinity, and a SNothing on the top is positive infinity
data ValidityInterval = ValidityInterval
  { invalidBefore :: !(StrictMaybe SlotNo),
    invalidHereafter :: !(StrictMaybe SlotNo)
  }
```

The proper implementation should be 

```
transVITime pp ei sysS (ValidityInterval SNothing (SJust i)) = do
  t <- slotToPOSIXTime pp ei sysS i
  pure $
    PV1.Interval
      (PV1.LowerBound PV1.NegInf True)
      (PV1.strictUpperBound t)
```

It seems it can't be easily fixed as it would change the on-chain behaviour.

**Comment by JaredCorduan** [comment]
I agree, this is a bug. The ledger is translating `[-∞, ttl_slot)` to `[-∞, ttl_posix]` inside the transaction context. Thank you for raising this @ak3n ! We will do our best to fix this at the next hardfork.

**Comment by koslambrou** [comment]
@JaredCorduan Is this something we can work on so that we can be sure it's going into the next HF?

**Comment by JaredCorduan** [comment]
> @JaredCorduan Is this something we can work on so that we can be sure it's going into the next HF?

yes, absolutely, thank you! I _think_ it should be an easy fix.

I suspect that this bug has never actually be exercised, though y'all might know better than me. In circumstances where a bug requires a hard fork to fix, and the fix is extremely localized, I recommend using the [HardFork](https://github.com/input-output-hk/cardano-ledger/blob/8b6f8e1a75034ca66fd66a39d437252eec927d71/eras/shelley/impl/src/Cardano/Ledger/Shelley/HardForks.hs) module technique. What's great is that `transVITime` already takes the protocol parameters as an input, so the change will be very minimal.

The ideas is very simple, we just switch on the major protocol version. We don't have time to get this into the upcoming intra-era hardfork, so we'll need to switch on major protocol version 9. Before 9, we support the bug, starting at 9 we do the correct thing. _After_ the hard fork, we can go back and see if the bug was ever exercised. If it was not, we can remove the switch altogether. If not, no worries, we just have to live with the wart forever.

The fix is probably about the same number of characters as this comment, so if you'd rather leave it to the ledger team, that's fine too. But I'm always excited to get more understanding between teams on how things work :).

**Comment by lehins** [comment]
Looks like this has bit some people in the wild after the hard fork. Here was my understanding of this when I analyzed this fix as a potential problem:

The only difference between theses two cases:
https://github.com/IntersectMBO/cardano-ledger/blob/fd46bf1c7891c68c6c47e009b659052a9fc64915/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Plutus/TxInfo.hs#L191-L195
is that the Conway case is:
```haskell
          Interval
            (LowerBound NegInf True)
            (LowerBound x False)
```
while pre-Conway is
```haskell
          Interval
            (LowerBound NegInf True)
            (LowerBound x True) -- <-- False is flipped
```
Any Plutus script that would be doing a pattern matching like this:

```haskell
case interval of
  Interval _ (LowerBound _ True) -> pass script
  Interval _ (LowerBound _ False) -> fail script
```
would ultimately change the behavior of the same transaction from passing phase2 validation to failing after the Conway boundary. In other words if a script ignored the value completely and made logic decisions solely on the information about the clusivity, then the semantics of the script would change.
However, as far as I understand this could be rectified by the user with supplying no upper bound at all which would translate to `Interval lowerBound (UpperBound PosInf True)`

Other than that checking for actual bounds were changed from `[a,b]` to `[a, b)`, which means supplying an interval in the transaction with `b+1` instead of `b` should bring the previous behavior for any script that relies on it.

**Comment by JaredCorduan** [comment]
by "bit people in the wild", you mean that the HF switch cannot be removed, or that some scripts post-HF noticed the change?

**Comment by lehins** [comment]
The latter:

> that some scripts post-HF noticed the change?

Some DApp developers ran into this, but it doesn't look like there are any problems, since all they have to do is adjust the values in the validity interval to match the behavior they expected previously.

@JaredCorduan Nothing to worry about the fix was good. :wink:
