### ISSUE TITLE
Pool's Sigma value truncated before leader calculation

### ISSUE THREAD

**Issue by AndrewWestberg** [IntersectMBO/cardano-ledger#3088]
Tagging @JaredCorduan for visibility.

I've gotten some reports from users of cncli leaderlogs that they have been inaccurate since the Babbage era. I have a few reports of both false-positive and false-negative leadership slots showing up.  It's infrequent and I haven't yet reproduced it on my own pools. I'm trying to ascertain whether cncli-leaderlogs have always been inaccurate, or whether this is something new with Babbage.

In cncli, I'm doing my best to represent the `FixedPoint` type in rust. On the haskell side, it appears that this should be using a 34-decimal digit value.

That being said, this line and in particular the conversion using `fromRational` is truncating the sigma value.

https://github.com/input-output-hk/cardano-ledger/blob/master/libs/cardano-protocol-tpraos/src/Cardano/Protocol/TPraos/BHeader.hs#L452

When I trace this value out on the haskell side, it is:
```
σ: 2.760820292047569e-3
```

on the Rust side, it is:
```
sigma: 0.0027608202920475691060291370008069
```

Is it possible that this inline conversion using `fromRational` is not using the `FixedPoint` type and thus artificially rounding the pool's sigma value?

If I add an interim step to the haskell code and force `fromRational` into a `FixedPoint` type on the haskell side, I then get the same value as rust:
```
σ: 0.0027608202920475691060291370008069
```

If this truncation has always been the case, I can adjust the code on the rust side to match. I just thought I'd file a bug to see if this is the intended behavior or not.

**Comment by JaredCorduan** [comment]
thanks @AndrewWestberg , I'll take a close look soon.

---

`Praos` is using the same code for this as `TPraos`, so nothing has changed recently. You can see here that `Praos` is just reusing the same `checkLeaderNatValue` function:

https://github.com/input-output-hk/ouroboros-network/blob/b9959087bfd72837c02b8b33ba04175e4ff8b186/ouroboros-consensus-protocol/src/Ouroboros/Consensus/Protocol/Praos.hs#L51-L52

https://github.com/input-output-hk/ouroboros-network/blob/b9959087bfd72837c02b8b33ba04175e4ff8b186/ouroboros-consensus-protocol/src/Ouroboros/Consensus/Protocol/Praos.hs#L518

---

I don't immediately see how `fromRational σ` would be truncating. Both `x` and `c` have type `FixedPoint`, `σ` has type `Ratio Integer`, so `fromRational σ` will convert `σ` from `Ratio Integer` to `FixedPoint` (which is indeed a 34 decimal value).

I'm confused why you would be seeing `σ` in scientific notation (since it is a `Ratio Integer`). are you just using something like `trace (show σ)`? Also, by "force fromRational into a FixedPoint type on the haskell side", do you mean:

```
foo :: FixedPoint
foo = fromRational σ
```
?

**Comment by AndrewWestberg** [comment]
@JaredCorduan Yes. that `foo` example is what I mean by force fromRational. Here is the commit where I forced it and then the display changed. note: *not a haskell dev.

https://github.com/AndrewWestberg/cardano-ledger/commit/db542956da2355523092136937f71e1fb1e15aec

**Comment by JaredCorduan** [comment]
thanks @AndrewWestberg , now I see what is going on! There's no truncation going on, it's just 

This line:
```
show (-fromRational σ))
```
probably isn't doing what you think it is doing. it's trying to turn a `Ratio Integer` into _something_ `Fractional` (which is a type class, not a type), and then convert that "fractional thing" into a string. Even though elsewhere you multiply `fromRational σ` by `c`, and it becomes clear that the `Fractional` type _should_ be a `FixedPoint`, poor `show` is left with vague instructions and makes the game time decision to convert to something like a `Float`, which it then displays in scientific notation.

If you try this:
```
foo = fromRational σ * c
sigma = trace (show foo) foo
```

you can then convince yourself that there is no intermediate rounding going on, and it should line up with your Rust code.

**Comment by AndrewWestberg** [comment]
Thanks @JaredCorduan. I'll keep digging. Seems my issue is elsewhere.

**Comment by lehins** [comment]
@AndrewWestberg This is a Haskell less known peculiarity.

If you look closer into the warning that GHC give's you on `show (-fromRational σ)` you will see something along the lines:
```
    • Defaulting the following constraints to type ‘Double’
        (Fractional a0)
```

That is because type checker implies:
```haskell
default (Integer, Double)
```
See "Default Numeric Types" section in [Numbers](https://www.haskell.org/tutorial/numbers.html) section of the Haskell 98 report.

That is why you see truncation and scientific notation, because type checker does not know the type of `(-fromRational σ)`, so it converts it to `Double` before showing it.

CC @JaredCorduan It is part of Haskell98 :wink:
