### ISSUE TITLE
earlier thunk for the per-stake-pool stake distribution

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3132]
This is a stop-gap measure for the problem described in #3034.

Create the thunk for the `calculatePoolDistr` when the corresponding snapshot is created (when crossing the previous epoch boundary), not in the `NEWEPOCH` rule. This way, when the consensus layer forecasts across the boundary multiple times, the expensive computation only happens once per epoch boundary per node per fork.

**Comment by JaredCorduan** [comment]
@nfrisby implemented the idea here: https://github.com/input-output-hk/cardano-ledger/tree/nfrisby/share-tickf-pooldistr-calculation

Nick may have done all the work already, we just need to see the idea through to completion.

**Comment by nfrisby** [comment]
I'm not sure where else to write this, so I'm putting it here (at least for now).

Jared and I had a called yesterday on this topic. Here is my summary:

- Context: the `TICK` rule actually ticks the full ledger state forward through time. The `TICKF` rule instead only ticks a partial "`LedgerView`" forward through time, but it's currently implemented by ticking _some_ of the actual ledger state forward, projecting our relevant parts of it, and then discarding the incoherent intermediate ledger state.

- The earlier thunk does prevent the node from paying the overhead of `calculatePoolDistr` more than once per epoch. 🙌

- Unfortunately, contrary to our expectations, it turns out that's not the dominant cost! 😞

- Instead of profiling, etc, I took a couple hours and swung for the fences: I refactored the `TICKF` impl on my branch (which Jared listed in the comment above and @aniketd is carrying forward) to skip all computation that is not necessary for constructing the `LedgerView`. So my `TICKF` there creates a _very_ incoherent "quasi-ticked" `NewEpochState` but that's safe because that state is only used to create a `LedgerView` and it is exactly the parts necessary to do so that my new `TICKF` rule does coherently update. This was a massive time-save; it's down to milliseconds (plus the one-time memoized cost of `calculatePoolDistr`), which has always been our general expectation. Thus, at the very least, this proves it can be _fast enough_ for Consensus's current architectural design.

There are four remaining concerns:

- The thunk for memoizing `calculatePoolDistr` is just a stop gap. It's a big benefit to calculate it once instead of "until someone gets lucky and manages to create a block in the new epoch" (drastically improving Issue input-output-hk/cardano-node#4421 ---- and also yielding a ~7% speedup in bulk sync, as a pleasant surprise). But it'd be even better if it were explicitly incrementalized across the epoch.

- My new `TICKF` was hastily made; I was just attempting a proof-of-concept and to unblock some related Genesis work for @amesgen. I would absolutely not merge it as-is: I think a ledger team member needs to independently implement the same "minimal" `TICKF`, carefully ensuring that the parts of `nes` it does update are updated exactly the same way that the proper `TICK` rule updates them. And maybe even profile the old `TICKF` first to have clarity on what was actually the most expensive part (I never did that: I instead ripped out everything I could, and it turns out that included the slow part, whatever it was.)

- Benchmarks. How can we prevent the epoch transition calculations from accidentally being way more expensive than we anticipated? Ideally these would be adjacent to the ledger code that implements them. However, creating chains of realistic size and complexity is difficult within this repo (a "`mainnet` chain" doesn't map to any single first-class concept in this repo), so a dedicated analysis pass in the `db-analyser` tool or a Consensus benchmark component (one increment downstream, in `ouroboros-network`) might be a sufficient compromise, for now.

- Some of the computation I removed from `TICKF` was sanity checks, which is unnerving. Jared and I discussed these. He explained that they are very much _sanity checks_--- if they were to fail when an honest node calls `TICKF` then that means `TICK` would also fail whenever the node eventually tries to truly advanced cross that same epoch boundary. In other words: whether these sanity checks fail is determined solely by ledger state parts that were fixed more than `k` blocks ago. Thus, it seems fine to remove them from `TICKF` and leave them in `TICK`: it doesn't affect whether the node fails, only (possibly) how promptly it fails.

cc @JaredCorduan please object to anything I messed up above!

**Comment by JaredCorduan** [comment]
Thank you for the excellent notes @nfrisby , I agree with it all.

We definitely still need to determine why `TICKF` is slow (outside of `calculatePoolDistr`).

One thing we can do to convince ourselves that the new minimal version of `TICKF` is acceptable it to write a property test that `getLedgerView . MinimalTICKF == getLedgerView . TICK`.

**Comment by JaredCorduan** [comment]
resolved by  #3209
