### ISSUE TITLE
Fix Mary era spec about the `mint` field

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3207]
In Haskell implementation `mint` field does not have the type `MaryValue` as of #2954 

We need to fix the spec to reflect the implmenetation. The biggest idea that should be conveyed through the spec, that there is a special type `MutliAsset` that cannot have any ADA associated with it, which makes it safe for minting. It is also the type that is used in `MaryValue`, thus making it reusable for sending multi assets.

Extra rule that was verifying that ada cannot be minted became completely redundant and was removed due to this change. This should also be updating in the spec.

**Comment by WhatisRT** [comment]
I don't think the spec should be updated - the change here is an implementation detail. In fact, updating the spec would be a big task, since it's generic over the notion of a Token algebra (so it can be a spec for both Mary and Allegra). Giving `mint` a special type means to define some kind of sub algebra just to talk about that type.

In fact I think the situation is fine as it is: there's a comment in the UTXO rule that the check isn't needed in the implementation. Anyone who is confused about this should be able to find that comment and not be confused anymore.

**Comment by lehins** [comment]
Sounds good with me
