### ISSUE TITLE
`Redeemers` and `MemoBytes`

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3236]
Investigate why `Redeemers` are based on `MemoBytes`, it doesn't seem like they need it.

If this is right then we should remove `MemoBytes` for `Redeemers`, since that only introduces unnecessary overhead.

**Comment by JaredCorduan** [comment]
The `Redeemers` are [included](https://github.com/input-output-hk/cardano-ledger/blob/3c4835dc4fe80a19f5714f576c49926d6a58c563/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L96) in the data used for the script integrity hash (since they are outside the transaction body and so we need a way to ensure that they are not manipulated.

Let's keep this issue to leave a better trail of documentation. :)

**Comment by lehins** [comment]
Yep, that is exactly were `MemoBytes` is being used: https://github.com/input-output-hk/cardano-ledger/blob/3c4835dc4fe80a19f5714f576c49926d6a58c563/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Tx.hs#L266-L284

We should add some documentation of the `Redeemers` and `TxDats` that explain what `MemoBytes` are being used for.
