### ISSUE TITLE
Zero-Quantity Assets in Block Data

### ISSUE THREAD

**Issue by yHSJ** [IntersectMBO/cardano-ledger#3240]
There is an inconsistency in what is allowed in the block data and what is stored in the ledger state for zero quantity assets in multi asset bundles. A quantity of zero in multi asset bundles is allowed in the block data but they are removed when the Cardano node deserializes the data.

This isn't a security issue at the ledger level, but it can cause confusion for end users and developers when other services deserialize block data themselves. While it can, and arguably should, be fixed at the application level, removing this inconsistency at the chain level would make it easier to build on top of the chain and reduces the chances that a developer displays information inconsistent with the ledger state that could easily be exploited. 

Here is an example change to the current CDDL that could be used to remove the zero quantity assets from the block data.
> negInt64 = -9223372036854775808 .. -1
 posInt64 = 1 .. 9223372036854775807
 nonZeroInt64 = negInt64 / posInt64 ; this is the same as the current int64 definition but without zero
 natNum = 1 .. 4294967295 ; non-zero 32bit uint
 mint = multiasset\<nonZeroInt64\>
 value = coin / [coin,multiasset\<natNum\>]

**Comment by JaredCorduan** [comment]
I agree, removing the zeros from the wire specification would remove confusion. Thanks for the idea for how to use CDDL to capture the change, that's wonderful!

**Comment by johnrichardrinehart** [comment]
Thanks for raising this issue. I'm not sure who would argue that this ought to be accounted for by end applications instead of restricting which transactions are considered valid by nodes (I'll guess it's the people who are responsible for authoring node software, though). But, as long as any information would/should otherwise be silently removed in exposing an API for querying ledger state then it ought not to be able to be written to the chain. My $.02.

**Comment by JaredCorduan** [comment]
I agree, I'd say that it is a [Non-Serious Flaw](https://github.com/cardano-foundation/CIPs/pull/372/files#diff-7111444883b4a66a658bafd1ca7472e3f26f31062cc535b5a30892bd6f740888R49).

EDIT: actually, this a bit interesting, since this change is a soft fork, meaning that node that are only validating do not need to upgrade. I think the upgrade path is different here, and should be made explicit in CIP-80.

**Comment by rvcas** [comment]
We love @yHSJ
