### ISSUE TITLE
Please turn on -Wmissing-import-lists

### ISSUE THREAD

**Issue by locallycompact** [IntersectMBO/cardano-ledger#3439]
I am using versions from CHaP, using the build plan specified by `cardano-node` - produced as a result of running:

```
nix build github:input-output-hk/cardano-node/master#project.x86_64-linux.plan-nix.json -o plan.json
```

relevant versions are here, which are the ones that I am using:

```
"cardano-ledger-binary-1.1.0.1-4dfc7b45882c15932e1b21e8ca21a140c225a8b30407267b8e602e6bff3681ed",
"cardano-ledger-byron-1.0.0.0-54be2730b8b028afc7e153fae3fc3793f0e58e30cbecf9086dcab8e78441d279",
```

I get build errors like this:

```
cardano-ledger-byron> src/Cardano/Chain/Update/Proposal.hs:188:18: error:
cardano-ledger-byron>     Ambiguous occurrence ‘annotation’
cardano-ledger-byron>     It could refer to
cardano-ledger-byron>        either the field ‘annotation’ of record ‘Annotated’,
cardano-ledger-byron>               imported from ‘Cardano.Ledger.Binary’ at src/Cardano/Chain/Update/Proposal.hs:62:3-16
cardano-ledger-byron>               (and originally defined in ‘cardano-ledger-binary-1.1.0.1:Cardano.Ledger.Binary.Decoding.Annotated’)
cardano-ledger-byron>            or the field ‘annotation’ of record ‘AProposal’,
cardano-ledger-byron>               defined at src/Cardano/Chain/Update/Proposal.hs:95:5
cardano-ledger-byron>     |
cardano-ledger-byron> 188 |   recoverBytes = annotation
cardano-ledger-byron>     |                  ^^^^^^^^^^
```

This is confusing, but would be far easier to diagnose if we would just keep explicit import lists.

**Comment by lehins** [comment]
It is pretty easy to diagnose the problem, the error message tells you exactly what's wrong. 

I appreciate your suggestion, but we will not be turning on `-Wmissing-import-lists` everywhere in the codebase. That being said, if you feel like submitting a PR with this warning enabled and explicit imports for the whole of byron codebase (`eras/byron/*`), I'll be happy to merge it.

Note, that you are trying to build the project with a newer ghc version that is not yet officially supported. This issue will be fixed in #3437
