### ISSUE TITLE
Constitution Committee Member expiry

### ISSUE THREAD

**Issue by JaredCorduan** [IntersectMBO/cardano-ledger#3443]
Each constitutional committee member will have their own specified epoch in which they are retired. This needs to be added to the CC cold/hot key map, something like: `Map (KeyHash 'CommitteeCold c) (KeyHash 'CommitteeHot c, Epoch)`.

The ledger rules need to enforce that the term limit is not past the protocol parameter that set the maximum.

~We have a decision still to make, the governance action that introduces a new committee member can either specify and epoch that the member retires or the duration (in epochs) until they retire.~ Duration is specified by a `CommitteeTermLimit` protocol parameter, which is specified in number of epochs.

**Comment by lehins** [comment]
* [ ] - Create a type:
```haskell
data CommiteeMember c 
  = CommitteeMemberActive
    -- | Hot credential for the active member
    !(Credential 'HotCommitteeRole c)
    -- | Epoch number when the member will expire
    !EpochNo
  | CommitteeMemberExpired
```

* [ ] - Change `CommitteeState`. Note removal of Maybe in favor of explicit type constructor:
```haskell
newtype CommitteeState era = CommitteeState
  { csCommitteeCreds ::
      Map
        (Credential 'ColdCommitteeRole (EraCrypto era))
        (CommiteeMember (EraCrypto era))
```

* [ ] - Addition of the expiration epoch number in the Enact rule

* [ ] - Implement Constitutional Committee expiry in the EPOCH rule.

**Comment by WhatisRT** [comment]
I've been thinking a little bit more about preventing changes to the hot key map for expired members, and I don't think we should prevent them.

The reason is consistency with other cases: we don't even check if the cold credential is in the CC when registering a hot credential (this is a feature, since it provides smoother CC transitions). So why should a credential that's been on the CC but expired have less power to do something than any other?

What we could do is treat the situation exactly like a credential that isn't on the CC: on the epoch boundary, we remove all credentials that aren't on the CC from the hot key map. We could include the expired ones here.

**Comment by lehins** [comment]
> What we could do is treat the situation exactly like a credential that isn't on the CC: on the epoch boundary, we remove all credentials that aren't on the CC from the hot key map. We could include the expired ones here.

This is even better! There is no point in keeping the expired ones around. I didn't even think about this. 


What about the ones that have resigned? When do we remove those from the Map? Two approaches I can think of. We could either:
* ~Remove them on the next boundary after they have resigned.~ I think this is a bad idea
* Or we can keep them around until the expire. The only reason I can think why would we do this is for error reporting and for transparency. People might want to see in the state that the CC member explicitly resigned.

**Comment by lehins** [comment]
Actually there is one more important reason I can think of for keeping around the resigned ones until they are expired. `NewCommittee` must specify the "old committee".

**Comment by lehins** [comment]
Ok, my earlier description (deleted) of how to solve this issue was totally wrong. After discussing it with @WhatisRT here is what needs to be done:

* [ ] - Inside the `NewCommitte` gov action we have a poorly named "Old Committee" (Haddock should state "Constitutional Committe members to be removed"). It is in fact Committee members that are being replaced by the new ones upon enactment. We need to verify that all of them exist in current `Committee.committeeMembers` upon proposal. We also need to remove them from the current Committee upon enactment. 

https://github.com/input-output-hk/cardano-ledger/blob/453d19da239d0eb123a98aabac2f74f5bfdb41f7/eras/conway/impl/src/Cardano/Ledger/Conway/Governance/Procedures.hs#L434-L441

* [ ] - New Committee members need to be added with the expiry EpochNo, which is computed from current epoch number and the `committeeTermLimit` PParam

* [ ] - All of the members that are not present in the current committee need to be removed from the CommitteeState (Cold+Hot credential mapping) in the VState. This must be done in the EPOCH rule after the ratification is complete.
