### ISSUE TITLE
Haddock is generated for hidden modules

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#3582]
It makes no sense to generate haddock for modules that can't be imported from outside of the package. This doesn't happen on Hackage and should not happen for Haddock that we generate for Ledger packages.

For example individuals rules are in the `other-modules` section, but Haddock is still generated: 

![image](https://github.com/input-output-hk/cardano-ledger/assets/2333894/5f537de2-88e7-40e9-b612-3402cda288bf)

**Comment by neilmayhew** [comment]
Unfortunately, #4257 didn't end up fixing this, so we can't close this ticket yet

**Comment by coot** [comment]
If you use `cabal haddock-project`, then this issue will resurface: haskell/cabal#10157; anyway if you decide to use `cabal haddock-project` then use `head` instead of `3.12.1.0` as it has some other fixes. We'll use it in `ouroboros-network` IntersectMBO/ouroboros-network#4944, we already use it for [io-sim](https://input-output-hk.github.io/io-sim).

**Comment by lehins** [comment]
#4578 didn't fix it either. Reopening.

@coot Thank you for suggestions!

@aniketd See if you can get `cabal haddock-project` to work.
