### ISSUE TITLE
Make it possible to refresh the DRep timeout

### ISSUE THREAD

**Issue by Soupstraw** [IntersectMBO/cardano-ledger#3621]
input-output-hk/formal-ledger-specifications#127 adds the possibility of submitting a ~`RegDRep`~ `UpdateDRepTxCert` certificate for an already existing DRep in order to reset the DRep expiration timer.

**Comment by lehins** [comment]
This actually is represented by the `UpdateDRepTxCert`:
https://github.com/input-output-hk/cardano-ledger/blob/3b1a42163c007afdef0a7ce49d3cf0236c554e23/eras/conway/impl/src/Cardano/Ledger/Conway/TxCert.hs#L274-L281

We don't want to use `RegDRepTxCert` for this purpose, because it requires a deposit, so it will look like we are either:
* collecting the deposit more than once
* or we allow zero deposits.

Neither of which are true, so for this purpose we created a specialized certificate, which serves two purposes:
* refreshes the timeout
* updates Anchor

I've updated the ticket description to reflect this
