### ISSUE TITLE
The ledger generates errors that break its own internal codec invariants in Conway

### ISSUE THREAD

**Issue by KtorZ** [IntersectMBO/cardano-ledger#3865]
See the discussions here: https://github.com/CardanoSolutions/ogmios/issues/346#issuecomment-1787736771

My assessment is that: 

- `ValueNotConserved` in the `*UtxoPredFailure` is a `Value`:
  - https://github.com/input-output-hk/cardano-ledger/blob/5c1c24bfc3a17b164e28c747fc8eb62503922f24/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxo.hs#L140-L145

- However, `Value` here is instantiated to a `MaryValue`, which, starting from the Conway era expects the Ada coin value to be non-null:

  - https://github.com/input-output-hk/cardano-ledger/blob/5c1c24bfc3a17b164e28c747fc8eb62503922f24/eras/mary/impl/src/Cardano/Ledger/Mary/Value.hs#L292-L299

Yet somehow, the ledger is able to produce a `ValueNotConserved` which contains a null Ada quantity, and it isn't able to de-serialize it back since it breaks its own invariant. It is slightly odd that this invariant is handled in the decoders rather than handled in the ledger rules (maybe it is too, but my point is that it should probably just be handled there since seemingly, it is possible to produce a null Ada quantity by other means anyway).

**Comment by lehins** [comment]
Thank you for this bug report.

Deserializers for predicate failures are not as important as they are for types that live on chain.

We can relax deserializer for `ValueNotConservedUTxO` to avoid this problem.

> It is slightly odd that this invariant is handled in the decoders rather than handled in the ledger rules (maybe it is too, but my point is that it should probably just be handled there since seemingly, it is possible to produce a null Ada quantity by other means anyway).

However, we are not going to change the deserializer for `MaryValue`, because it is important that we get well formed data over the wire. In the matter of fact we were able to expose and fix other warts in the system thanks to this deserializer.

**Comment by lehins** [comment]
> Deserializers for predicate failures are not as important as they are for types that live on chain.

Just to make sure I do not trigger anyone, I am not trying to say that they are not important, because they are. They are just less important, because a bug in a predicate failure will result in tools failing, rather than the whole blockchain failing, which could be the case with types that go on chain.

**Comment by KtorZ** [comment]
> @lehins: We can relax deserializer for ValueNotConservedUTxO to avoid this problem.

I am not sure that this is the right strategy; because the problem will likely occur on any `Value era` type in any of the ledger predicate failures. Doing it case-by-case is an easy way to miss a case (now or later, as new predicate failures are added). 

Given that the `Value era` from `ValueNotConservedUTxO` (and probably some other failures) can actually hold a zero value of Ada, perhaps the type should reflect that? Something like `DeltaValue` or similar that would convey this.

**Comment by lehins** [comment]
I thought about this over the weekend and realized that it will be too much work to relax deserializer just for the predicate failure, precisely because it would require introduction not just an extra type, but a whole new type family. So I decided to take the easy route and go with your suggestion, which is to allow 0 ADA value for the `MaryValue`. There is still a change in Conway that 0 amount in MultiAssets will result in a deserialization failure, but that is an impossible case in the type itself anyways.

We do have a `BabbageOutputTooSmallUTxO` predicate check that will ensure that a TxOut's have at least a minimum amount, therefore 0 ADA is not possible in `MaryValue` in `TxOut` anyways, as long as the `CoinsPerUTxOByte` PParam stays positive.

Here is PR with the fix: #3867 in particular this commit: 14e7278b2fe0dfb433354f3f5594f84a4f2a3dc3

**Comment by lehins** [comment]
Fixed in #3867
