### ISSUE TITLE
Fix flakiness in a property test

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4076]
This test has been failing for years now (See #1638). Which makes it a useless test in presence of randomness

```
      We are elected as leader proportional to our stake:                    FAIL (6.64s)
        *** Failed! Falsified (after 89 tests and 19 shrinks):
        ASC (ActiveSlotCoeff {unActiveSlotVal = 4993816495258313 % 18014398509481984, unActiveSlotLog = -3246400179917455809567734387442081})
        StakeProportion (143882283013 % 274877906944)
        247 /< 378 /< 378 (p=0.15627595358256552)
        Use --quickcheck-replay=529930 to reproduce.
        Use -p '/We are elected as leader proportional to our stake/' to rerun this test only.
```

We do need to get rid of this failure on CI, since it is getting in a way of development.
The proper way would be to investigate the reason and fix in a way that it could never fail in presence of randomness, however that seems to be pretty hard considering the nature of the test.  Therefore, instead of removing or disabling the test we should hard code a set seed on that test which would essentially convert this property test into a unit test.

**Comment by neilmayhew** [comment]
After a lot of thought, I've concluded that we should just delete this test. It's testing the same thing as the previous test (`checkLeaderVal succeeds iff l < 1 - (1-f)^r`) but in a non-deterministic way. Effectively, it's just testing the algorithm used for the test (a binomial probability distribution) and not the production code that's being used in the test. That code is tested far more effectively by the previous test.

Keeping it as a unit test with a set seed would be a little tricky because AFAICT you can force a seed only on an individual generator (with  `Gen.variant`) or on an entire program (by tweaking the options). It could be done by generating the `f` and `r` argument values explicitly (with `arbitrary`), making a combined generator that returns a `(f, r, vrfVals)` tuple, and wrapping that with `Gen.variant`. However, I don't think it's worth the trouble, and leaving the test in is just confusing since it doesn't really add anything.

**Comment by lehins** [comment]
It's actually not that hard. It requires reaching for some internal QuickCheck modules, but that's ok, since they are pretty stable. Check it out:
```haskell
ghci> import Test.QuickCheck
ghci> import Test.QuickCheck.Gen
ghci> import Test.QuickCheck.Random
ghci> let runGen i (MkGen f) = f (mkQCGen i) 30
ghci> runGen 2024 (arbitrary :: Gen Int)
15
```

**Comment by neilmayhew** [comment]
> `runGen i (MkGen f) = f (mkQCGen i) 30`

That's more or less what I thought `variant` did, but I was wrong. I also forgot that I could use the `Monad` instance of `Gen` to make a combined generator for all the random values in the test.

I've now defined a similar function called `withSeed` that returns `Gen a` rather than `a`, so I can use it as a combinator:
```
withSeed i (QC.MkGen f) = QC.MkGen $ \_r n -> f (QC.mkQCGen i) n
```
