### ISSUE TITLE
alonzo spec delta changes for treasury and reserves from MIR certs are unclear

### ISSUE THREAD

**Issue by zuzunker** [IntersectMBO/cardano-ledger#4077]
![image](https://github.com/IntersectMBO/cardano-ledger/assets/5585355/87f4759a-1f7b-47bb-aae2-52427db4e59b)

Alonzo spec describes this change for the MIR certs processing, with the new `deltaReserves` and `deltaTreasury` values produced from MIR certs of the type `[ 0 / 1, coin ]` that are supposed to move funds directly between pots. The question is related to the `MIR` transition still using only the `totT` and `totR` values to change the actual pots, and these values are produced only from aggregating the `irwdT` and `irwdR`, so only the certs with staking keys. It seems like the `deltaReserves` and `deltaTreasury` values are only used to calculate the `enough` value and are not used to change the actual pots.

It also seems from the MIR rule that the validation is not correct since if checks if `totR` is less or equal to `treasury + deltaTreasury`, but then produces `acnt'` with `treasury - totT`, which means, for example, the treasury technically might become negative in case `totT > treasury` but `totT <= (treasury + deltaTreasury)`.

Am I missing something?

**Comment by WhatisRT** [comment]
Good catch! In the `enough` case of `acnt'`, it should say `availableTreasury - totT` and the same for the reserves, otherwise these could indeed go negative.

I also checked, that's what's implemented: https://github.com/IntersectMBO/cardano-ledger/blob/master/eras/shelley/impl/src/Cardano/Ledger/Shelley/Rules/Mir.hs#L139
