### ISSUE TITLE
Shelley spec `NEWPP` clarification for MIR

### ISSUE THREAD

**Issue by zuzunker** [IntersectMBO/cardano-ledger#4098]
![image](https://github.com/IntersectMBO/cardano-ledger/assets/5585355/43608af0-476f-4861-9658-87dfe3810337)

The `NEWPP` transition in the Shelley spec describes this precondition for the `reserves + diff` to be greater than the sum of all MIR certificate values.

But the `MIR` transition always happens before the `NEWPP` transition and it always wipes the `Irwd` state empty, as far as I understand.

Does this precondition makes sense or it can be simplified to check `reserves + diff >= 0`?

**Comment by WhatisRT** [comment]
Yeah, I think you're right. Note that the rhs doesn't even type-check: `i_rwd` contains two maps, but this is written as if it's just a single map. I assume that this check was moved to `MIR` (there are two checks like this there) and then not properly adjusted here. In fact, the implementation doesn't contain that line at all (at least not in NEWPP). @lehins do you know if this check is implemented anywhere? Because if not, you could violate preservation of Ada by having empty reserves, a registered pool or stake credential and raising the deposit. I'd be surprised if the tests missed that.

Now this isn't an issue in practice, since we're completely ripping this out in Conway and the deposits never changed and they won't until Conway (there are other good reasons for that beside this one).

**Comment by zuzunker** [comment]
> Now this isn't an issue in practice, since we're completely ripping this out in Conway and the deposits never changed and they won't until Conway (there are other good reasons for that beside this one).

Thank you, @WhatisRT! Yup, for the future it's not an issue. I just need to know if I might have missed something in the spec where MIRs would not be empty by the moment NEWPP happens for any previous epochs

**Comment by lehins** [comment]
I can't find anything that is even remotely relevant to mir certificates and `reserves + diff >= sum Mir` check in `NEWPP` rule. That being said, I don't understand why that cehck is necessary in the first place, since we already check that `reserves >= sum (iRReserves Mir)` and `treasury >= sum (iRTreasury Mir)` in the `MIR` rule. Which is a stronger check than the one highlighted in this ticket.

It seems to me like an unnecessary (an ill typed, as @WhatisRT pointed out) check.

> you could violate preservation of Ada by having empty reserves, a registered pool or stake credential and raising the deposit.

Sorry, I fail to see how StakePool and StakingCredential deposits are relevant to MIR certificates and the amount in the reserves. Could you elaborate more on this?

**Comment by WhatisRT** [comment]
The issue here is not the `MIR` part, but `reserves + diff >= 0`. If this is violated, the reserves in `acnt'` go negative, and the way to violate it is to increase the deposits. Now this is fixed by tracking individual deposits as we do now, but before we had that I think this needed to be prevented somehow. Maybe the check was removed when individual deposit tracking was implemented?

**Comment by lehins** [comment]
OK, this is definitely not an issue. In our implementation `diff` can't be anything but `0`.

Reason for this is because a change to protocol parameters cannot affect the `obligation` calculation, since we track each individual deposit. There used to be a problem with deposits not being tracked, which is when a change to deposits would have lead to violation of ADA preservation. But now this is all fixed, not only for Conway, but also all way to Shelley.

Which means we can completely remove this obligation calculation from the spec or set the diff to `0`, to emphasize that parameter change does not immediately affect any of the ada pots

**Comment by TimSheard** [comment]
In the old days, all the deposits were kept in one big pot. And the amount that was added to the deposit pot was controlled by one of the PParams., So if the PParams changed, there had to be enough money some where to cover the the change in the what the refunds would be, in case everyone  deregistered  to get their refunds. So there had to be some kind of check that there was enough money somewhere. I think that extra money (both positive and negative, depending on how the PParams changed) was the reserves. So I suspect that summation had to do with this anomaly. By the way this anomally was a security threat, because if one had knowledge that this PParam was changing, one could game the system.

Now all deposits are accounted for individually,  and refunds are exactly what was paid for the deposit, and NOT a function of the Deposit PParam at the time the refund was made.

**Comment by lehins** [comment]
@WhatisRT So, do we wanna fix the spec for the NEWPP rule, or should I just close the ticket?

**Comment by WhatisRT** [comment]
This is a weird scenario. The spec isn't broken, since this line is required for preservation of Ada, but the code is also not broken since we're doing something else entirely with deposits. I guess the only thing that we could do is to change the Shelley spec to also keep track of individual deposits, but that's a lot of effort for very little gain. I think doing nothing is fine.
