### ISSUE TITLE
Shelley spec `NEWPP` weird definition

### ISSUE THREAD

**Issue by zuzunker** [IntersectMBO/cardano-ledger#4099]
![image](https://github.com/IntersectMBO/cardano-ledger/assets/5585355/f3214673-a36a-4b1b-8dc3-6ac8bb401ff7)

The `NEWPP` transition in the Shelley spec makes this weird definition for `olbg_cur = deposited`, but that value is never used for anything and that's the only usage for the `deposited`, which is mentioned as used, but in reality seems useless.

Am I missing something?

**Comment by WhatisRT** [comment]
Note that this line doesn't define `oblg_cur`, it's an equality check. `oblg_cur` and `deposited` are both defined above from different pieces of the state. This equality check seems somewhat stupid though, because it asserts that the deposits owed are the same as the deposits we have, which should always be true. I believe that this came from the Isabelle formalization of Shelley. The better way to do this would have been to prove this as an invariant instead of asserting it here, but it doesn't really make a big difference in practice. Does this answer your question?

**Comment by zuzunker** [comment]
> Note that this line doesn't define `oblg_cur`, it's an equality check. `oblg_cur` and `deposited` are both defined above from different pieces of the state. This equality check seems somewhat stupid though, because it asserts that the deposits owed are the same as the deposits we have, which should always be true. I believe that this came from the Isabelle formalization of Shelley. The better way to do this would have been to prove this as an invariant instead of asserting it here, but it doesn't really make a big difference in practice. Does this answer your question?

Ahhh, I have completely confused the assigning and a check. Thank you, @WhatisRT !
