### ISSUE TITLE
Haddock building is broken

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4156]
It seems that there is an issue with [github pages on CI](https://github.com/IntersectMBO/cardano-ledger/actions/runs/8143972981/job/22257035670), in particular, there is an issue building haddock

**Comment by lehins** [comment]
Something seems to be off. There are no failures any more but I can't find the same builds happening on master any more

We need to investigate and confirm github pages and haddock updating works as expected.

We also need to ensure we overwrite previous commits, so we do not retain this huge history of useless html files. In other words we need to reduce the size of `gh-pages` branch.

**Comment by neilmayhew** [comment]
The builds are [happening](https://github.com/IntersectMBO/cardano-ledger/actions/workflows/gh-pages.yml) and have been successful since merging #4157.

There's a separate [deployment process](https://github.com/IntersectMBO/cardano-ledger/deployments/github-pages) that runs whenever the `gh-pages` branch is updated.

The Haddocks at https://cardano-ledger.cardano.intersectmbo.org/ do reflect the latest changes on `master`. For example, [Test.Cardano.Ledger.Conway.ImpTest](https://cardano-ledger.cardano.intersectmbo.org/cardano-ledger-conway%3Atestlib/Test-Cardano-Ledger-Conway-ImpTest.html) has my `NonEmpty` changes in it.

Looking at the list of deployments, it seems that the benchmarks workflow also writes to `gh-pages`, about 1h before the Haddocks one finishes, and the Haddocks workflow overwrites the benchmark results. I don't think the two types of output are merged, unfortunately.

Previous commits *are* being overwritten on the `gh-pages` branch. The branch is force-updated to be the tip of `master` with one extra commit containing the Haddock output. While this does avoid having old files kept around, it also causes the benchmark results to be lost rather than merged.

Shall we open a separate issue to address the overwriting of the benchmark results?

**Comment by lehins** [comment]
Very nice. Thank you for confirming this @neilmayhew 

> Shall we open a separate issue to address the overwriting of the benchmark results?

No one really looks at those benchmarks. So, I don't think we need to worry about them at this point, but creating a ticket about this is certainly a good idea.

**Comment by neilmayhew** [comment]
This has broken again, as a result of #4176, and because the Haddock build currently uses `nix develop` to get an environment.

I'll change it to use a bare environment similar to what the regular Haskell build does (in [haskell.yml](https://github.com/IntersectMBO/cardano-ledger/blob/master/.github/workflows/haskell.yml))

**Comment by neilmayhew** [comment]
As a side-effect of it being broken, I discovered that the benchmark run _does_ merge its results with any existing content, but the Haddock run doesn't work that way and always finishes later.
