### ISSUE TITLE
Adjust stake pool distribution calculation

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4171]
Current stake distribution calculation does not consider the amount in the reward account if there are no addresses in the UTxO associated with the stake credential

In order to fix that we need to iterate over the delegations in the UMap instead of the incremental stake map: https://github.com/IntersectMBO/cardano-ledger/blob/3311e074cd3ea25262439b284d9966ef60fce4d6/eras/shelley/impl/src/Cardano/Ledger/Shelley/LedgerState/IncrementalStake.hs#L220

~It is important to fix this behavior for Conway only with the branch on a hardfork.~ Not an issue

This work will also require an imp test that checks that having ADA in the reward account with no associated stake in the UTxO does affect the distribution in Conway, but not in prior eras.

**Comment by TimSheard** [comment]
I am having trouble understanding this. 
The stake distribution is define by this equation
```
(dom poolDelegs) ◁ (aggregate+ (credStake ∪ ptrStake ∪ rewards))
```
We compute it using this equivalent formulation
```
aggregate+ ((dom poolDelegs ◁ credStake) ∪ (dom poolDelegs ◁ ptrStake) ∪ (dom poolDelegs ◁ rewards))
```
The discussion above seems to indicate that there is something wrong with `(dom poolDelegs ◁ credStake) ` but I don't think that is the case.  If we are missing things from the rewards, then those must come from this computation `(dom poolDelegs ◁ rewards))`.

Either the computation is incorrect, or the way we combine the two is incorrect. 

Now the `rewards ` part of the UMap keeps track of both earned rewards and deposits paid to register the credential.  Which of those two do we include in the the distribution attributed to rewards? 

Finally, how do we combine the two? I think this is where we go wrong.

So I created a test that checks the assertion that the _Current stake distribution calculationdoes not consider the amount in the reward account if there are no addresses in the UTxO associated with the stake credential_ to be False. It does indeed add the stake in rewards accounts even if that credential does not appear in any UTxO entry. So its seems that  ` (dom poolDelegs ◁ rewards)` is doing its job correctly.

**Comment by TimSheard** [comment]
I think it is worthwhile to think critically about what goes into a Distribution. A distribution sums up all the Coin controlled by 
each entity, across some Set of Ada Pots. It would have a type like: (Map entityId Coin).

All Coin in the system is stored in one of the 6 Ada pots.
```
data AdaPots = AdaPots
  { treasuryAdaPot :: Coin
  , reservesAdaPot :: Coin
  , rewardsAdaPot :: Coin
  , utxoAdaPot :: Coin
  , feesAdaPot :: Coin
  , obligationsPot :: Obligations
  }
```
The Obligations is a way further breaking down the Deposits into 4 sub-Pots.  Deposits are obligations because they must eventually be paid back. If they didn't have to be paid back, then they would be 'gifts' or 'fees', not 'deposits'.
```
data Obligations = Obligations
  { oblStake :: !Coin  -- deposits for registering a Credential
  , oblPool :: !Coin    -- deposits for creating a Pool
  , oblDRep :: !Coin   -- deposits for registering as a DRep
  , oblProposal :: !Coin   -- deposits when making a new Proposal
  }
```
So the **treasury,** **reserves** and **fees** are controlled by the system, so those Coins should not appear in any Distribution. That leaves the Coin stored in the UtxO, the rewards, and the deposits. 

So I'd like to introduce a slightly different meaning for the work 'Stake',  Stake is a generic term for the Coin controlled by an entity. So there are six different kinds of 'Stake' one for each of the Ada pots that can be used as the source of Coin in a Distribution. These terms are new, but help us make exact distinctions about what is going on. Each entity may control one or more kinds of stake.

So the available Set of Ada Pots that could be used to define a Distribution is:

1. **utxo Stake**           (coin in the UtxO)
2. **reward Stake**       (earned rewards)
3. **credential Stake**   (deposits paid to register a Credential)
4. **pool Stake**            (deposits paid to register a Pool)
5. **drep Stake**           (deposits paid to register as a DRep)
6. **proposal Stake**    (deposits paid to make a new Proposal)

So the Classic Distribution is what we have been calling the stake distribution. It sums the Coin for each staking credential from the Set of Ada Pots { **utxo Stake** , **reward Stake** }. 

We also have two other Distributions, which I would call delegating Distributions. Currently entities delegate to Pools and DReps. So it makes sense to talk about Pool distributions and DRep distributions. Here the sum is not over the entity that controls the Coin, but to the set of entities that the "Coin Controllers" delegate to. Currently we have 2 such distributions. 

pool distributions allow entities to delegate their **utxo Stake** and their **reward Stake**
drep distributions allow entities to delegate their **utxo Stake**

There is no reason we can't allow entities to delegate additional kinds of Stake. In fact it would be quite easy.

**Comment by lehins** [comment]
I can see now why this works. It is the merging here:
https://github.com/IntersectMBO/cardano-ledger/blob/3311e074cd3ea25262439b284d9966ef60fce4d6/eras/shelley/impl/src/Cardano/Ledger/Shelley/LedgerState/IncrementalStake.hs#L241-L252
that adds those rewards that don't have any other stake associated with the stake credential, except rewards.

Once #4211 is merged we can close this ticket, since it will add a test that verifies that this behaves as expected.

**Comment by lehins** [comment]
A test has been added that confirms the correct behavior in #4242
