### ISSUE TITLE
constrained-generators: flaky call to error in GenT

### ISSUE THREAD

**Issue by aniketd** [IntersectMBO/cardano-ledger#4466]
There was a call to `error` observed in [this job](https://github.com/IntersectMBO/cardano-ledger/actions/runs/9781063488/job/27008391166?pr=4457).

This seems to be a rare occurrence, as none of the other GHC versions surfaced this and re-running the job also made the tests pass.

**Comment by lehins** [comment]
Looks like we haven't see this issue for a long time. Most likely it was fixed

@aniketd FYI, I recommend for the future in tickets like this to also include all the steps necessary to reproduce the failure as well the relevant part of output of the failure. Linking to CI run is not sufficient, since those logs get cleaned up after some time.
