### ISSUE TITLE
`GovInfoEvent` incorrectly reports removed as enacted

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4602]
Currently `GovInfoEvent` event reports all the removed siblings of enacted actions also as enacted, instead of just removed from the state.

That could lead to confsuing bugs downstream from ledger and therefore need ot be fixed by adding a new field to the event that records removal of conflicting proposals.

**Comment by lehins** [comment]
CC @kderme 
This bug is probably affecting db-sync

**Comment by kderme** [comment]
Thank you for pinging. I think we actually used the event correctly, ie as a signal for the refunds returned and not as a signal for enactment. We used it as a signal for enactment only for actions that don't have parents (withdrawals and info). For all other actions we used the Proposals tree roots at the start of each epoch. This approach was quite hacky, so this pr is welcome :+1: 

Btw, can an action be at the same time dropped due to expiration of its parent and enacted at the same time? This wouldn't affect the ledger, but it would affect the interpretation of the event by db-sync.

**Comment by lehins** [comment]
> Btw, can an action be at the same time dropped due to expiration of its parent and enacted at the same time? 

No that can't happen. By definition GovAction cannot be enacted, if its parent didn't get enacted. In other words, as soon as GovAction expires, all of its descendants are also removed from the state as expired
