### ISSUE TITLE
Remove usage of git submodule for `cardano-mainnet-mirror`

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/cardano-ledger#4749]
Reported by @michalrus:
```
❯ git clone  --recurse-submodules=never https://github.com/IntersectMBO/cardano-ledger.git
Cloning into 'cardano-ledger'...
remote: Enumerating objects: 179162, done.
remote: Counting objects: 100% (1276/1276), done.
remote: Compressing objects: 100% (514/514), done.
remote: Total 179162 (delta 998), reused 854 (delta 676), pack-reused 177886 (from 1)
Receiving objects: 100% (179162/179162), 113.63 MiB | 2.24 MiB/s, done.
Resolving deltas: 100% (101207/101207), done.
error: object eb6fb9bef41871323404b2c19e23fb5550ef04c9: gitmodulesUrl: disallowed submodule url: https://github.com/:input-output-hk/cardano-mainnet-mirror.git
fatal: fsck error in pack objects
fatal: index-pack failed
```

> The submodule URL has a colon where it should have a slash: https://github.com/:… instead of https://github.com/….

We do not use `cardano-mainnet-mirror` aside from some byron era tests. We retrieve that repo differently on CI, so we do not need it as a git submodule. It should be removed.

**Comment by michalrus** [comment]
@neilmayhew found the real reason. It's a historical object:

```
❯ git log -p --all --find-object=eb6fb9bef41871323404b2c19e23fb5550ef04c9
```

a9f02e929b59dcd863cec8dfbb9c283d872f89c1 (bug):
```patch
commit a9f02e929b59dcd863cec8dfbb9c283d872f89c1
Author: Damian Nadales <damian.nadales@iohk.io>
Date:   Wed Nov 28 17:42:37 2018 -0300

    Change ssh to https in .gitmodules for hydra to work.

diff --git a/.gitmodules b/.gitmodules
index 7ff8c5d10..eb6fb9bef 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,3 +1,3 @@
 [submodule "cardano-mainnet-mirror"]
    path = cardano-mainnet-mirror
-   url = git@github.com:input-output-hk/cardano-mainnet-mirror.git
+   url = https://github.com/:input-output-hk/cardano-mainnet-mirror.git
```

192100f52500fae497de60ef7d6c26d321c1e05e (fix):
```patch
commit 192100f52500fae497de60ef7d6c26d321c1e05e
Author: Damian Nadales <damian.nadales@iohk.io>
Date:   Wed Nov 28 17:48:04 2018 -0300

    Correct typo in .gitmodules

diff --git a/.gitmodules b/.gitmodules
index eb6fb9bef..e479438d3 100644
--- a/.gitmodules
+++ b/.gitmodules
@@ -1,3 +1,3 @@
 [submodule "cardano-mainnet-mirror"]
    path = cardano-mainnet-mirror
-   url = https://github.com/:input-output-hk/cardano-mainnet-mirror.git
+   url = https://github.com/input-output-hk/cardano-mainnet-mirror.git
```

But the history was not rewritten then, and if you clone with automatic `git-fsck` turned on, it is still being detected, and the clone fails. The setting in `~/.gitconfig` is:

```
[transfer]
        fsckObjects = true
```

**Comment by michalrus** [comment]
A one-time workaround:
```
❯ git --config-env transfer.fsckObjects=false clone https://github.com/IntersectMBO/cardano-ledger.git
```

**Comment by neilmayhew** [comment]
The stronger check in `git fsck` was added in January 2024. It was introduced in this [patch thread](https://lore.kernel.org/git/pull.1635.git.1704822817.gitgitgadget@gmail.com/) in the git mailing list. One [review response](https://lore.kernel.org/git/20240110102338.GA16674@coredump.intra.peff.net/) said this:

> By making it an fsck check, though, any mistakes that are embedded in history (even if they are now corrected) will make it a pain to use the repository with sites that enable transfer.fsckObjects.
>
> My gut feeling is that this is probably OK in practice. If it does cause pain, we might consider loosening the fsck.gitmodulesUrl severity (under the notion from above that it is no longer a critical security check). But if it doesn't cause real-world pain, being pickier is probably better (it may save us from a vulnerability down the road).

**Comment by neilmayhew** [comment]
I've written a [response](https://lore.kernel.org/git/d9f53fe7-6570-4aea-894c-942e12e012c4@mayhew.name/T/#t) asking if loosening could now be considered, since a significant real-world example of pain has been identified.

**Comment by lehins** [comment]
Rewriting history is obviously not an option. Therefore it looks like we can close this issue as won't fix, since there isn't really anything that we can do in order to avoid this problem.

If I am wrong and someone has a cute idea about how to deal with this, please reopen the issue with such suggestion.

**Comment by neilmayhew** [comment]
The git maintainers are open to downgrading the fsck message to a warning instead of an error. This is an easy fix and I'm in the process of submitting a patch for it.

The maintainers did make me aware of a better way to handle this in our own repo, however. There's a repo config option to specify a "skiplist" file containing a list of objects that shouldn't have semantic checks applied to them. In our case, this is just one object (the blob of the `.gitattributes` file that existed briefly). This option works well, and enables `fsck` in our repo to complete successfully without errors or warnings.

I propose we create a hidden file called `.git-fsck-skiplist`, similar to the `.git-blame-ignore-revs` we have already, containing the offending blob hash. We then add a small note at the end of the `README` mentioning this problem that's embedded in the repo history, and telling people to run `git config fsck.skipList .git-fsck-skiplist` if they plan on using `git fsck`. Unfortunately, I don't know of a way to set this automatically, other than putting it in a `shellHook` that gets run by `nix develop` whenever it starts.

This won't help someone who has `transfer.fsckObjects` enabled and wants to clone, but we can mention in the note the command-line config option they can use to set the skiplist or downgrade the error to a warning.

It's annoying to have to clutter up our `README` with this info, but I think we have an obligation to at least mention it, and if we put it at the end of the `README` perhaps it won't be *too* annoying. What do you think?

**Comment by neilmayhew** [comment]
I made a PR for it since I had all the information to hand, and even if we don't merge it the information is now recorded somewhere.
